/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainshoping;

import java.util.Map;

/**
 *
 * @author omare
 */
public class Category_list extends javax.swing.JPanel {

    /**
     * Creates new form Category_list
     */
    admin Admin;
    category cat;
    public Category_list(admin d,category cat) {
        initComponents();
        this.Admin=d;
        this.cat=cat;
        this.lblcatid.setText(String.valueOf(cat.getId()));
        this.lblcatname.setText(cat.getName());
        for (Map.Entry<Integer, item> en : cat.Items.entrySet()) {
            Integer key = en.getKey();
            item value = en.getValue();
            Cat_item ci =new Cat_item(Admin,value);
            this.pnlitemlist.add(ci);
            this.validate();
            this.repaint();                       
        }
    }
    
    public Category_list() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcatname = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlitemlist = new javax.swing.JPanel();
        lblcatid = new javax.swing.JLabel();
        lbldeltecat = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(870, 345));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcatname.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblcatname.setText("Category Name");
        jPanel1.add(lblcatname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 188, 10));

        pnlitemlist.setBackground(new java.awt.Color(102, 0, 102));
        pnlitemlist.setAutoscrolls(true);
        pnlitemlist.setMaximumSize(new java.awt.Dimension(0, 140));
        pnlitemlist.setMinimumSize(new java.awt.Dimension(0, 140));
        pnlitemlist.setLayout(new javax.swing.BoxLayout(pnlitemlist, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(pnlitemlist);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 850, 240));

        lblcatid.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblcatid.setText("Category ID");
        jPanel1.add(lblcatid, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 15, -1, -1));

        lbldeltecat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldeltecat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        lbldeltecat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldeltecatMouseClicked(evt);
            }
        });
        jPanel1.add(lbldeltecat, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 30, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lbldeltecatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldeltecatMouseClicked
        // TODO add your handling code here:       
        Admin.categories.remove(cat.getId());       
    }//GEN-LAST:event_lbldeltecatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcatid;
    private javax.swing.JLabel lblcatname;
    private javax.swing.JLabel lbldeltecat;
    private javax.swing.JPanel pnlitemlist;
    // End of variables declaration//GEN-END:variables
}
