/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainshoping;

import java.util.Map;
import java.util.TreeMap;

/**
 *
 * @author Ahmed Gamal
 */
public class show_all_bills extends javax.swing.JPanel {

    /**
     * Creates new form show_all_all
     */
    admin Admin;
    public show_all_bills(admin d) {
        initComponents();       
        for (Map.Entry<Integer, customer> entry : Admin.users.entrySet()) {
            Integer key = entry.getKey();
            customer value = entry.getValue();
            Map.Entry<Integer, cart> unread= (Map.Entry<Integer, cart>) value.getUnreadingcarts();
         
         usertobill lml=new  usertobill((TreeMap<Integer, cart>) unread,value,this);         
         this.pnlread.add(lml);
            
         this.validate();
         this.repaint();
         
        }
        
        
    }
    public show_all_bills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlread = new javax.swing.JPanel();
        pnlshowbill = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlread.setBackground(new java.awt.Color(204, 0, 0));
        pnlread.setLayout(new java.awt.GridLayout(20, 2, 2, 0));
        jPanel1.add(pnlread, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 790));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 248, 787));

        pnlshowbill.setLayout(new javax.swing.BoxLayout(pnlshowbill, javax.swing.BoxLayout.PAGE_AXIS));
        add(pnlshowbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 820, 790));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlread;
    public javax.swing.JPanel pnlshowbill;
    // End of variables declaration//GEN-END:variables

    private void getReadingcarts() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
