/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainshoping;

import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed Gamal
 */
public class user_operations extends javax.swing.JFrame {

    /**
     * Creates new form user_Main
     */
    customer cust;
    admin Admin;
    public user_operations(admin d , customer cu) {
        initComponents();
        this.Admin=d;
        this.cust = cu;
        lblusername.setText("Name : " + cu.getFirst_name() + " " + cu.getLast_name());
        lbluserid.setText("ID : " + cu.getId());
    }
    public user_operations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        lbluserid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnlogoutuser = new javax.swing.JButton();
        btnmainuser = new javax.swing.JButton();
        btnmycartuser = new javax.swing.JButton();
        btnprofileuser = new javax.swing.JButton();
        pnluseroperations = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblusername.setText("Name :");
        jPanel2.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 11, -1, -1));

        lbluserid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbluserid.setText("ID :");
        jPanel2.add(lbluserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("User Operations");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 60));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogoutuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnlogoutuser.setText("Log out");
        btnlogoutuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutuserActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogoutuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 100, 60));

        btnmainuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnmainuser.setText("Main");
        btnmainuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmainuserActionPerformed(evt);
            }
        });
        jPanel3.add(btnmainuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        btnmycartuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnmycartuser.setText("My Cart");
        btnmycartuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmycartuserActionPerformed(evt);
            }
        });
        jPanel3.add(btnmycartuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 100, 60));

        btnprofileuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnprofileuser.setText("Profile");
        btnprofileuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofileuserActionPerformed(evt);
            }
        });
        jPanel3.add(btnprofileuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1260, 60));

        pnluseroperations.setLayout(new javax.swing.BoxLayout(pnluseroperations, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(pnluseroperations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1250, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmainuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmainuserActionPerformed
        // TODO add your handling code here:

        this.pnluseroperations.removeAll();
        this.transferFocus();
        this.pnluseroperations.add(new user_main_operation(Admin,cust));
        this.setVisible(true);

        this.pnluseroperations.setVisible(true);

//        this.pnluseroperations.setLayout(new BorderLayout());
        this.validate();
        this.repaint();

    }//GEN-LAST:event_btnmainuserActionPerformed

    private void btnmycartuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmycartuserActionPerformed

        this.pnluseroperations.removeAll();
        this.transferFocus();
        this.pnluseroperations.add(new user_cart_operation(Admin,cust,this));
        this.pnluseroperations.setVisible(true);
        this.validate();
        this.repaint();

    }//GEN-LAST:event_btnmycartuserActionPerformed

    private void btnprofileuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofileuserActionPerformed
        this.pnluseroperations.removeAll();
        this.transferFocus();
        this.pnluseroperations.add(new profile_user(Admin,cust));
        this.pnluseroperations.setVisible(true);
        this.validate();
        this.repaint();
    }//GEN-LAST:event_btnprofileuserActionPerformed

    private void btnlogoutuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutuserActionPerformed
        Sign signin_form = new Sign(Admin);
        
        signin_form.reduser.setSelected(true);
        signin_form.transferFocus();
        signin_form.validate();
        signin_form.repaint();
          signin_form.setVisible(false);
        signin_form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnlogoutuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_operations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogoutuser;
    private javax.swing.JButton btnmainuser;
    private javax.swing.JButton btnmycartuser;
    private javax.swing.JButton btnprofileuser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbluserid;
    private javax.swing.JLabel lblusername;
    public javax.swing.JPanel pnluseroperations;
    // End of variables declaration//GEN-END:variables
}
