/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainshoping;

import java.util.TreeMap;

/**
 *
 * @author Ahmed Gamal
 */
public class usertobill extends javax.swing.JPanel {

    /**
     * Creates new form usertobill
     */
    admin Admin;
    cart c;
    TreeMap<Integer,cart> unread;
    customer cust;
    show_all_bills frm ;
    public usertobill(TreeMap<Integer,cart> unread,customer cust,show_all_bills frm) {
        initComponents();
        this.unread= unread;
        this.frm=frm;
        this.cust=cust;
    }
    public usertobill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 18, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("ahmed gamal");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 11, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
   
      
        frm.transferFocus();
        frm.pnlshowbill.add(new Bill_info(unread ,cust));
        frm.pnlshowbill.setVisible(true);
        frm.validate();
        frm.repaint();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
