/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainshoping;

import java.awt.Component;
import java.awt.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author omare
 */
public class user_main_operation extends javax.swing.JPanel {

    /**
     * Creates new form user_main_operation
     */
    admin Admin;
    customer cust;
    public user_main_operation(admin d,customer cust) {
        initComponents();
        this.cust=cust;
        this.Admin= d;
       
            for(int i = 0 ; i < Admin.categories.size() ; i++)
            {
                cat_calling_check cat = new cat_calling_check();
                cat.categorycb.setText(Admin.categories.get(i).getName());                
                pnlcats.add(cat);
            }
        
    }
    public user_main_operation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btngetcats = new javax.swing.JButton();
        pnlcats = new javax.swing.JPanel();
        pnlcatlists = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Categories");

        jSeparator1.setForeground(new java.awt.Color(102, 0, 51));

        btngetcats.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btngetcats.setText("GO");
        btngetcats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetcatsActionPerformed(evt);
            }
        });

        pnlcats.setBackground(new java.awt.Color(204, 255, 204));
        pnlcats.setLayout(new java.awt.GridLayout(20, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btngetcats))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pnlcats, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlcats, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btngetcats)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlcatlists.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlcatlists, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlcatlists, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btngetcatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetcatsActionPerformed
        ArrayList<String> list=new ArrayList<String>();
        Component [] coms=this.pnlcats.getComponents();
        for (Component com : coms) {
            if(com instanceof JPanel)
            {
                JPanel pnl1 =(JPanel) com;
                Component[] cb=pnl1.getComponents();
                JCheckBox catcb=(JCheckBox)cb[0];
                if(catcb.isSelected())
                {
                    list.add(catcb.getText());                    
                }
            }
        }
        TreeMap<Integer,category>mycats=new TreeMap<Integer,category>();
        for (Map.Entry<Integer, category> entry : Admin.categories.entrySet()) {
            Integer key = entry.getKey();
            category value = entry.getValue();
            for (int i = 0; i < list.size(); i++) {
                String get = list.get(i);
                if(value.getName().equals(get))
                {
                    mycats.put(key, value);
                }
                
            }
            
        }
        
           for (Map.Entry<Integer, category> entry : mycats.entrySet()) {
            Integer key = entry.getKey();
            category value = entry.getValue();            
            this.pnlcatlists.add(new Category_list(Admin,value));
            this.validate();
            this.repaint();
            
        }
        
         
    }//GEN-LAST:event_btngetcatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngetcats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlcatlists;
    private javax.swing.JPanel pnlcats;
    // End of variables declaration//GEN-END:variables
}
